apiVersion: v1
kind: Service
metadata:
  name: gopher-db
spec:
  ports:
    - port: 5432
  selector:
    app: gopher-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopher-db
spec:
  selector:
    matchLabels:
      app: gopher-db
  template:
    metadata:
      labels:
        app: gopher-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "gopher"
        - name: POSTGRES_PASSWORD
          value: "secret"
        - name: POSTGRES_DB
          value: "gopherqueue"
        ports:
        - containerPort: 5432