apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopher-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gopher-control
  template:
    metadata:
      labels:
        app: gopher-control
    spec:
      containers:
      - name: control-plane
        image: gopher-control:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        env:
        - name: DATABASE_URL
          value: "postgres://gopher:secret@gopher-db:5432/gopherqueue?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: gopher-control
spec:
  selector:
    app: gopher-control
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051