// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/v1/task.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReportStatus
type TaskState int32

const (
	TaskState_PENDING   TaskState = 0
	TaskState_RUNNING   TaskState = 1
	TaskState_COMPLETED TaskState = 2
	TaskState_FAILED    TaskState = 3
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "COMPLETED",
		3: "FAILED",
	}
	TaskState_value = map[string]int32{
		"PENDING":   0,
		"RUNNING":   1,
		"COMPLETED": 2,
		"FAILED":    3,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_api_proto_v1_task_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{0}
}

// SubmitTask
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      string                 `protobuf:"bytes,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_api_proto_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_api_proto_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// GetWork
type WorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_api_proto_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *WorkRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type WorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	mi := &file_api_proto_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *WorkResponse) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *WorkResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	PercComplete  float32                `protobuf:"fixed32,3,opt,name=perc_complete,json=percComplete,proto3" json:"perc_complete,omitempty"`
	CurrState     TaskState              `protobuf:"varint,4,opt,name=curr_state,json=currState,proto3,enum=queue_service.TaskState" json:"curr_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerUpdate) Reset() {
	*x = WorkerUpdate{}
	mi := &file_api_proto_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerUpdate) ProtoMessage() {}

func (x *WorkerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerUpdate.ProtoReflect.Descriptor instead.
func (*WorkerUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerUpdate) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *WorkerUpdate) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerUpdate) GetPercComplete() float32 {
	if x != nil {
		return x.PercComplete
	}
	return 0
}

func (x *WorkerUpdate) GetCurrState() TaskState {
	if x != nil {
		return x.CurrState
	}
	return TaskState_PENDING
}

type ServerSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancel        bool                   `protobuf:"varint,1,opt,name=cancel,proto3" json:"cancel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerSignal) Reset() {
	*x = ServerSignal{}
	mi := &file_api_proto_v1_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSignal) ProtoMessage() {}

func (x *ServerSignal) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSignal.ProtoReflect.Descriptor instead.
func (*ServerSignal) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{5}
}

func (x *ServerSignal) GetCancel() bool {
	if x != nil {
		return x.Cancel
	}
	return false
}

var File_api_proto_v1_task_proto protoreflect.FileDescriptor

const file_api_proto_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/task.proto\x12\rqueue_service\"`\n" +
	"\vTaskRequest\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\tR\btaskType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\"C\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\"*\n" +
	"\vWorkRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"A\n" +
	"\fWorkResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xa2\x01\n" +
	"\fWorkerUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12#\n" +
	"\rperc_complete\x18\x03 \x01(\x02R\fpercComplete\x127\n" +
	"\n" +
	"curr_state\x18\x04 \x01(\x0e2\x18.queue_service.TaskStateR\tcurrState\"&\n" +
	"\fServerSignal\x12\x16\n" +
	"\x06cancel\x18\x01 \x01(\bR\x06cancel*@\n" +
	"\tTaskState\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\xe7\x01\n" +
	"\fQueueService\x12E\n" +
	"\n" +
	"SubmitTask\x12\x1a.queue_service.TaskRequest\x1a\x1b.queue_service.TaskResponse\x12B\n" +
	"\aGetWork\x12\x1a.queue_service.WorkRequest\x1a\x1b.queue_service.WorkResponse\x12L\n" +
	"\fReportStatus\x12\x1b.queue_service.WorkerUpdate\x1a\x1b.queue_service.ServerSignal(\x010\x01B3Z1github.com/yourusername/gopher-queue/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_task_proto_rawDescOnce sync.Once
	file_api_proto_v1_task_proto_rawDescData []byte
)

func file_api_proto_v1_task_proto_rawDescGZIP() []byte {
	file_api_proto_v1_task_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_task_proto_rawDesc), len(file_api_proto_v1_task_proto_rawDesc)))
	})
	return file_api_proto_v1_task_proto_rawDescData
}

var file_api_proto_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_v1_task_proto_goTypes = []any{
	(TaskState)(0),       // 0: queue_service.TaskState
	(*TaskRequest)(nil),  // 1: queue_service.TaskRequest
	(*TaskResponse)(nil), // 2: queue_service.TaskResponse
	(*WorkRequest)(nil),  // 3: queue_service.WorkRequest
	(*WorkResponse)(nil), // 4: queue_service.WorkResponse
	(*WorkerUpdate)(nil), // 5: queue_service.WorkerUpdate
	(*ServerSignal)(nil), // 6: queue_service.ServerSignal
}
var file_api_proto_v1_task_proto_depIdxs = []int32{
	0, // 0: queue_service.WorkerUpdate.curr_state:type_name -> queue_service.TaskState
	1, // 1: queue_service.QueueService.SubmitTask:input_type -> queue_service.TaskRequest
	3, // 2: queue_service.QueueService.GetWork:input_type -> queue_service.WorkRequest
	5, // 3: queue_service.QueueService.ReportStatus:input_type -> queue_service.WorkerUpdate
	2, // 4: queue_service.QueueService.SubmitTask:output_type -> queue_service.TaskResponse
	4, // 5: queue_service.QueueService.GetWork:output_type -> queue_service.WorkResponse
	6, // 6: queue_service.QueueService.ReportStatus:output_type -> queue_service.ServerSignal
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_task_proto_init() }
func file_api_proto_v1_task_proto_init() {
	if File_api_proto_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_task_proto_rawDesc), len(file_api_proto_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_task_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_task_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_task_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_task_proto_msgTypes,
	}.Build()
	File_api_proto_v1_task_proto = out.File
	file_api_proto_v1_task_proto_goTypes = nil
	file_api_proto_v1_task_proto_depIdxs = nil
}
